# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyelection',
            name='contained',
            field=models.BooleanField(default=False, verbose_name='Width Restrictive Container?'),
            preserve_default=False,
        ),
    ]
